### ISSUE TITLE
Installing dependencies locally instead of globally?

### ISSUE THREAD

**Issue by iDams** [plotly/academy#7]
Hey,

In your tutorial, you tell people to install `browserify` and `watchify` globally with the `-g` option.
Is it on purpose?

IMO, this is not a good practice to install something globally. People can forget sometimes that a dependency is needed for a project because they have installed it a while ago globally. Just my opinion though!

**Comment by mxstbr** [comment]
Absolutely agree, this only happens in the introduction – afterwards everything is local and run with `npm scripts`! The problem is that with local installations you don't get access to the CLI command, which is why for exemplary purposes in the intro I tell people to globally install those modules.
